---
title: "JoinedData"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{JoinedData}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(ape)
library(rotl)
library(remotes)
library(datelife)
```

```{r}
read.csv(file = "../data-raw/IUCN Red List Changes - 2002 to 2022 - Single Measure.csv") -> Single_Measure
read.csv(file = "../data-raw/IUCN Red List Changes - 2002 to 2022 - Multiple Measures.csv") -> Multiple_Measure
```

```{r}
intersect(colnames(Single_Measure), colnames(Multiple_Measure))
```

```{r}
inner_join(Single_Measure, Multiple_Measure, by = "Year") %>% 
  filter(Year == "2018") %>% 
  head()
```

 Two datasets that are joined to see the total amount of species threatend to becoming endangered in the year of 2018
 
```{r}
inner_join(Single_Measure, Multiple_Measure, by = "Year") %>% 
  select(Year, Class, Metric, Number.of.Species) %>% 
  group_by(Metric) %>% 
  mutate(Species = as.integer(Number.of.Species)) %>% 
  filter(!is.na(Species)) %>% 
  ggplot() +
  geom_line(mapping = aes(x = Year, y = Species, color = Metric)) +
  facet_wrap(~Class, scales = "free_y")
```
Graphs that show the two dataset joined to assess how endangered each species are from the early 2000's to present day. Similar to the previous data as most species are threatned to becoming endangered
